"use client";

import { useEffect, useState } from "react";
import { Download, FileArchive, Loader2, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";

type ArtifactItem = { id: string; name: string; format: string; status: string; size: number | null; version: number; scope: string; error: string | null; createdAt: string };

function sizeLabel(size: number | null) { return size === null ? "-" : size < 1024 * 1024 ? `${(size / 1024).toFixed(0)} KB` : `${(size / 1024 / 1024).toFixed(1)} MB`; }

export function ArtifactList({ initial }: { initial: ArtifactItem[] }) {
  const [items, setItems] = useState(initial), [busy, setBusy] = useState<string>(), [error, setError] = useState("");
  async function refresh() { const response = await fetch("/api/artifacts", { cache: "no-store" }); if (response.ok) setItems(await response.json()); }
  useEffect(() => { if (!items.some((item) => ["PENDING", "PROCESSING"].includes(item.status))) return; const timer = setInterval(() => refresh().catch(() => undefined), 2000); return () => clearInterval(timer); }, [items]);
  async function remove(id: string) { if (!confirm("Hapus artifact ini secara permanen?")) return; setBusy(id); const response = await fetch(`/api/artifacts/${id}`, { method: "DELETE" }); if (response.ok) setItems((old) => old.filter((item) => item.id !== id)); else setError((await response.json().catch(() => null))?.error ?? "Artifact gagal dihapus"); setBusy(undefined); }
  async function regenerate(id: string) { setBusy(id); const response = await fetch(`/api/artifacts/${id}`, { method: "POST" }); if (!response.ok) setError((await response.json().catch(() => null))?.error ?? "Artifact gagal dibuat ulang"); await refresh(); setBusy(undefined); }
  return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm">{error && <p className="border-b bg-red-50 px-5 py-3 text-sm text-red-700">{error}</p>}<div className="hidden grid-cols-[minmax(0,1fr)_90px_100px_190px] gap-4 border-b bg-slate-50 px-5 py-3 text-xs font-semibold uppercase tracking-wide text-slate-500 sm:grid"><span>File</span><span>Format</span><span>Ukuran</span><span>Aksi</span></div>{items.length ? items.map((artifact) => <div key={artifact.id} className="grid gap-3 border-b px-5 py-4 last:border-0 sm:grid-cols-[minmax(0,1fr)_90px_100px_190px] sm:items-center"><div className="flex min-w-0 items-center gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-teal-50 text-teal-700">{["PENDING", "PROCESSING"].includes(artifact.status) ? <Loader2 className="size-5 animate-spin" /> : <FileArchive className="size-5" />}</span><span className="min-w-0"><span className="block truncate font-medium text-slate-800">{artifact.name}</span><span className="mt-0.5 flex items-center gap-1 text-xs text-slate-400"><ShieldCheck className="size-3" /> {artifact.scope} · v{artifact.version} · {new Date(artifact.createdAt).toLocaleDateString("id-ID")}</span>{artifact.error && <span className="block text-xs text-red-600">{artifact.error}</span>}</span></div><span className="text-xs font-bold text-slate-500">{artifact.format}</span><span className="text-sm text-slate-500">{sizeLabel(artifact.size)}</span><span className="flex gap-2">{artifact.status === "READY" && <a href={`/api/artifacts/${artifact.id}`} title="Unduh" className="rounded-lg bg-teal-700 p-2 text-white"><Download className="size-4" /></a>}<button onClick={() => regenerate(artifact.id)} disabled={busy === artifact.id} title="Buat versi baru" className="rounded-lg border p-2 text-slate-600 disabled:opacity-40"><RefreshCw className="size-4" /></button><button onClick={() => remove(artifact.id)} disabled={busy === artifact.id} title="Hapus" className="rounded-lg border p-2 text-red-600 disabled:opacity-40"><Trash2 className="size-4" /></button><span className="self-center text-xs font-medium text-amber-600">{artifact.status !== "READY" ? artifact.status : ""}</span></span></div>) : <div className="px-6 py-16 text-center text-sm text-slate-400">Belum ada artifact tersimpan.</div>}</section>;
}