import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Bot, Building2, CheckCircle2, FlaskConical, UserPlus, Users } from "lucide-react";
import { auth } from "@/auth";
import { BrandLogo } from "@/app/brand-logo";
import { db } from "@/lib/db";
import { getOllamaModels } from "@/lib/ollama";
import { getAllowedModels } from "@/lib/settings";
import { assignUnit, createEvaluationCase, createUnit, createUser, resetPassword, runEvaluation, saveModels, toggleUser } from "./actions";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ models?: string }> }) {
  const session = await auth();
  if (session?.user.role !== "ADMIN") redirect("/chat");
  const status = (await searchParams).models;
  const [users, units, evaluationCases, evaluationRuns, auditEvents] = await Promise.all([
    db.user.findMany({ orderBy: { createdAt: "desc" }, select: { id: true, username: true, name: true, role: true, active: true, unitId: true, unit: { select: { code: true } } } }),
    db.unit.findMany({ orderBy: { code: "asc" } }), db.ragEvaluationCase.findMany({ orderBy: { createdAt: "desc" }, take: 10 }),
    db.ragEvaluationRun.findMany({ orderBy: { createdAt: "desc" }, take: 10, include: { _count: { select: { results: true } } } }),
    db.auditEvent.findMany({ orderBy: { createdAt: "desc" }, take: 30, include: { user: { select: { username: true } } } }),
  ]);
  const allowed = await getAllowedModels();
  let available: string[] = [], online = true;
  try { available = await getOllamaModels(); } catch { online = false; available = allowed; }
  return <main className="min-h-screen bg-slate-100">
    <header className="border-b bg-slate-950 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div className="flex items-center gap-3"><BrandLogo className="size-10 rounded-lg" /><div><p className="font-semibold">Administrasi PLTGU AI</p><p className="text-xs text-slate-400">Pengguna dan model</p></div></div><Link href="/chat" className="flex items-center gap-2 text-sm text-slate-300"><ArrowLeft className="size-4" /> Kembali</Link></div></header>
    <div className="mx-auto grid max-w-7xl gap-6 p-6 lg:grid-cols-3">
      <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><UserPlus className="text-teal-700" /><h2 className="font-bold">Buat pengguna</h2></div><form action={createUser} className="space-y-4">{[["name","Nama lengkap","text"],["username","Username","text"],["password","Password sementara","password"]].map(([name,label,type]) => <label key={name} className="block text-sm font-medium">{label}<input name={name} type={type} required minLength={name === "password" ? 10 : 2} className="mt-1.5 w-full rounded-lg border px-3 py-2.5 outline-none focus:border-teal-500" /></label>)}<label className="block text-sm font-medium">Role<select name="role" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"><option value="USER">User</option><option value="ADMIN">Admin</option></select></label><label className="block text-sm font-medium">Unit<select name="unitId" className="mt-1.5 w-full rounded-lg border px-3 py-2.5"><option value="">Tanpa unit</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.code} - {unit.name}</option>)}</select></label><button className="w-full rounded-lg bg-teal-700 px-4 py-2.5 font-semibold text-white">Buat akun</button></form></section>
      <section className="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-2"><div className="mb-5 flex items-center gap-3"><Users className="text-teal-700" /><h2 className="font-bold">Daftar pengguna</h2><span className="ml-auto rounded-full bg-slate-100 px-3 py-1 text-xs">{users.length} akun</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-400"><tr><th className="py-3">Pengguna</th><th>Role</th><th>Unit</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{users.map((u) => <tr key={u.id} className="border-b border-slate-100"><td className="py-4"><b>{u.name}</b><p className="text-xs text-slate-500">@{u.username}</p></td><td>{u.role}</td><td><form action={assignUnit} className="flex"><input type="hidden" name="id" value={u.id} /><select name="unitId" defaultValue={u.unitId ?? ""} className="rounded-l-md border px-2 py-1 text-xs"><option value="">-</option>{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.code}</option>)}</select><button className="rounded-r-md bg-slate-700 px-2 text-xs text-white">Simpan</button></form></td><td className={u.active ? "text-emerald-700" : "text-red-600"}>{u.active ? "Aktif" : "Nonaktif"}</td><td><div className="flex flex-wrap gap-2"><form action={toggleUser}><input type="hidden" name="id" value={u.id} /><button className="rounded-md border px-2 py-1 text-xs">{u.active ? "Nonaktifkan" : "Aktifkan"}</button></form><form action={resetPassword} className="flex"><input type="hidden" name="id" value={u.id} /><input name="password" type="password" required minLength={10} placeholder="Password baru" className="w-28 rounded-l-md border px-2 py-1 text-xs" /><button className="rounded-r-md bg-slate-800 px-2 py-1 text-xs text-white">Reset</button></form></div></td></tr>)}</tbody></table></div></section>
      <section className="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-3"><div className="mb-4 flex items-center gap-3"><Building2 className="text-teal-700" /><h2 className="font-bold">Unit / Divisi</h2></div><form action={createUnit} className="flex flex-wrap gap-2"><input name="code" required placeholder="Kode unit" className="rounded-lg border px-3 py-2" /><input name="name" required placeholder="Nama unit/divisi" className="min-w-72 flex-1 rounded-lg border px-3 py-2" /><button className="rounded-lg bg-teal-700 px-4 py-2 font-semibold text-white">Tambah unit</button></form><div className="mt-4 flex flex-wrap gap-2">{units.map((unit) => <span key={unit.id} className="rounded-full bg-slate-100 px-3 py-1 text-sm"><b>{unit.code}</b> · {unit.name}</span>)}</div></section>
      <section className="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-3"><div className="mb-5 flex items-center gap-3"><Bot className="text-teal-700" /><div><h2 className="font-bold">Model Ollama</h2><p className="text-sm text-slate-500">Pilih model yang dapat digunakan.</p></div><span className={`ml-auto flex items-center gap-1 text-sm ${online ? "text-emerald-700" : "text-red-600"}`}><CheckCircle2 className="size-4" /> {online ? "Terhubung" : "Tidak terhubung"}</span></div>{status === "saved" && <p className="mb-4 rounded-lg bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700">Pilihan model berhasil disimpan. Model aktif ditandai centang.</p>}{status === "empty" && <p className="mb-4 rounded-lg bg-amber-50 px-4 py-3 text-sm font-medium text-amber-800">Pilih minimal satu model sebelum menyimpan.</p>}<form action={saveModels}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{available.map((m) => <label key={m} className="flex cursor-pointer items-center gap-3 rounded-xl border p-4 hover:border-teal-500 hover:bg-teal-50"><input type="checkbox" name="models" value={m} defaultChecked={allowed.includes(m)} className="size-5 accent-teal-700" /><span className="font-mono text-sm">{m}</span></label>)}{!available.length && <p className="text-sm text-slate-500">Belum ada model terdeteksi.</p>}</div><button type="submit" disabled={!available.length} className="mt-5 rounded-lg bg-teal-700 px-5 py-2.5 font-semibold text-white hover:bg-teal-800 disabled:cursor-not-allowed disabled:opacity-40">Simpan model</button></form></section>
      <section className="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-3"><div className="mb-5 flex items-center gap-3"><FlaskConical className="text-teal-700" /><div><h2 className="font-bold">Evaluasi kualitas RAG</h2><p className="text-sm text-slate-500">Metrik deterministik retrieval, sitasi, grounding, dan latensi.</p></div></div><div className="grid gap-6 lg:grid-cols-2"><form action={createEvaluationCase} className="space-y-3"><input name="name" required placeholder="Nama kasus" className="w-full rounded-lg border px-3 py-2" /><textarea name="question" required placeholder="Pertanyaan evaluasi" className="min-h-24 w-full rounded-lg border px-3 py-2" /><textarea name="expectedAnswer" placeholder="Jawaban/kata kunci yang diharapkan (opsional)" className="min-h-20 w-full rounded-lg border px-3 py-2" /><input name="expectedSources" placeholder="Sumber harapan, pisahkan koma (nama/ID)" className="w-full rounded-lg border px-3 py-2" /><button className="rounded-lg bg-teal-700 px-4 py-2 font-semibold text-white">Tambah kasus</button><div className="space-y-2">{evaluationCases.map((item) => <div key={item.id} className="rounded-lg bg-slate-50 p-3 text-sm"><b>{item.name}</b><p className="text-slate-600">{item.question}</p></div>)}</div></form><div><form action={runEvaluation} className="mb-4 flex gap-2"><select name="model" className="flex-1 rounded-lg border px-3 py-2">{allowed.map((model) => <option key={model}>{model}</option>)}</select><button disabled={!allowed.length || !evaluationCases.length} className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white disabled:opacity-40">Jalankan suite</button></form><div className="space-y-2">{evaluationRuns.map((run) => { const summary = run.summary as { groundedRate?: number; citationScore?: number; latencyMs?: number } | null; return <div key={run.id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between"><b>{run.model}</b><span>{run.status}</span></div><p className="text-slate-500">{run._count.results} hasil · Grounded {summary ? `${Math.round((summary.groundedRate ?? 0) * 100)}%` : "-"} · Sitasi {summary ? `${Math.round((summary.citationScore ?? 0) * 100)}%` : "-"} · {summary?.latencyMs ? `${Math.round(summary.latencyMs)} ms` : "-"}</p></div>; })}</div></div></div></section>
      <section className="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-3"><h2 className="mb-4 font-bold">Audit tata kelola terbaru</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-400"><tr><th className="py-2">Waktu</th><th>Aktor</th><th>Aksi</th><th>Entitas</th><th>Unit</th></tr></thead><tbody>{auditEvents.map((event) => <tr key={event.id} className="border-b"><td className="py-2">{event.createdAt.toLocaleString("id-ID")}</td><td>{event.user?.username ?? "sistem"}</td><td>{event.action}</td><td>{event.entityType ?? "-"}{event.entityId ? ` · ${event.entityId.slice(0, 8)}` : ""}</td><td>{event.unitId ?? "-"}</td></tr>)}</tbody></table></div></section>
    </div>
  </main>;
}